version: '3.8'

services:
  # 1. Database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: eduops_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Ho_Chi_Minh
    ports:
      # Map ra cổng 5433 để tránh xung đột với Postgres cài trên máy thật của Host
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eduops_network
    restart: unless-stopped

  # 2. Redis Cache
  redis:
    image: redis:7-alpine
    container_name: eduops_redis
    ports:
      # Map ra cổng 6380 để tránh xung đột với Redis cài trên máy thật
      - "6380:6379"
    volumes:
      - redisdata:/data
    networks:
      - eduops_network
    restart: unless-stopped

  # 3. .NET 8 Backend
  backendeduopssaas:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eduops_backend
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Link trực tiếp tới service 'db' và 'redis' qua network nội bộ của Docker
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=${REDIS_CONNECTION}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # Mount file appsettings.json từ máy Host vào Container lúc runtime (rất quan trọng)
      - ./backend/EduOps.Api/appsettings.json:/app/appsettings.json:ro
    depends_on:
      - db
      - redis
    networks:
      - eduops_network
    restart: unless-stopped

  # 4. Next.js Frontend
  frontendeduopssaas:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduops_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api # URL để Client fetch API từ Host
      - INTERNAL_API_URL=http://backendeduopssaas:8080/api # Cho NextAuth Server side kết nối nội bộ
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - backendeduopssaas
    networks:
      - eduops_network
    restart: unless-stopped

  # 5. Nginx API Gateway / Proxy Layer
  nginx:
    image: nginx:alpine
    container_name: eduops_nginx
    ports:
      - "80:80"   # Nginx sẽ nhận traffic từ ngoài vào ở port 80
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontendeduopssaas
      - backendeduopssaas
    networks:
      - eduops_network
    restart: unless-stopped

networks:
  eduops_network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
